import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Debord Company || Porfolio personal de Mario Sanz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
